name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup pnpm
      uses: pnpm/action-setup@v1.2.1
      with:
        version: 5.18.1
        run_install: true
    - name: Prettier check
      run: pnpm run fmt:check
    - name: Download previous code
      uses: actions/checkout@v2
      with:
        ref: 'dist'
        path: 'dist'
    - name: Build
      run: pnpm run build
    - name: Commit and push
      run: |
        cd dist
        git config user.email g-plane@hotmail.com
        git config user.name 'Pig Fang'
        git add .
        git commit -m 'build' && git push origin dist || true
